#!/usr/bin/env node
/**
 * scripts/generate-docs.js
 *
 * Parses fresh-normalize.css and generates a CSS API reference
 * as a Markdown file. Run via: npm run docs:build
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const css = readFileSync(join(ROOT, 'fresh-normalize.css'), 'utf-8');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8'));

// ─── Extract sections ─────────────────────────────────────────────────────────
function extractSections(cssContent) {
  const sectionRegex = /\/\* =+\n\s+(\d+\.\s+.+?)\n\s+=+ \*\/\n([\s\S]*?)(?=\/\* =+|$)/g;
  const sections = [];
  let match;
  while ((match = sectionRegex.exec(cssContent)) !== null) {
    sections.push({
      title: match[1]?.trim() ?? '',
      content: match[2]?.trim() ?? '',
    });
  }
  return sections;
}

// ─── Extract custom properties ────────────────────────────────────────────────
function extractCustomProperties(cssContent) {
  const props = [];
  const regex = /\s+(--fn-[\w-]+):\s*([^;]+);(?:\s*\/\*([^*]+)\*\/)?/g;
  let match;
  while ((match = regex.exec(cssContent)) !== null) {
    const name = match[1]?.trim() ?? '';
    const value = (match[2]?.trim() ?? '').replace(/\s+/g, ' ');
    const comment = match[3]?.trim() ?? '';
    if (!props.find((p) => p.name === name)) {
      props.push({ name, value, comment });
    }
  }
  return props;
}

// ─── Extract selectors with their comments ────────────────────────────────────
function extractSelectorsWithComments(sectionContent) {
  const rules = [];
  const blockRegex = /\/\*\*?\n([\s\S]*?)\*\/\s*\n([\s\S]*?)\{/g;
  let match;
  while ((match = blockRegex.exec(sectionContent)) !== null) {
    const comment = (match[1] ?? '')
      .replace(/^\s*\*\s?/gm, '')
      .trim()
      .replace(/\n+/g, ' ');
    const selector = (match[2] ?? '').trim().replace(/\s+/g, ' ');
    if (selector && comment) {
      rules.push({ selector, comment });
    }
  }
  return rules;
}

// ─── Build Markdown ────────────────────────────────────────────────────────────
const sections = extractSections(css);
const customProps = extractCustomProperties(css);
const today = new Date().toISOString().split('T')[0];

let md = `# fresh-normalize CSS API Reference

> Auto-generated from \`fresh-normalize.css\` — Do not edit manually.
> Last updated: ${today} | Version: ${pkg.version}

## Table of Contents

`;

sections.forEach((s, i) => {
  const anchor = s.title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-');
  md += `${i + 1}. [${s.title}](#${anchor})\n`;
});

md += `\n---\n\n`;

// Custom properties section
md += `## CSS Custom Properties (\`--fn-*\`)\n\n`;
md += `All configurable values are exposed as CSS custom properties. Override in \`:root\`:\n\n`;
md += `\`\`\`css\n:root {\n  --fn-focus-color: #7c3aed;\n  --fn-font-sans: 'Inter', system-ui, sans-serif;\n}\n\`\`\`\n\n`;
md += `| Property | Default Value | Notes |\n`;
md += `|----------|---------------|-------|\n`;

customProps.forEach(({ name, value, comment }) => {
  const truncatedValue = value.length > 60 ? value.substring(0, 57) + '...' : value;
  md += `| \`${name}\` | \`${truncatedValue}\` | ${comment} |\n`;
});

md += `\n---\n\n`;

// Each CSS section
sections.forEach((section) => {
  md += `## ${section.title}\n\n`;
  const rules = extractSelectorsWithComments(section.content);
  if (rules.length > 0) {
    rules.forEach(({ selector, comment }) => {
      md += `### \`${selector}\`\n\n${comment}\n\n`;
    });
  }
  md += `---\n\n`;
});

md += `\n*Generated by \`scripts/generate-docs.js\`*\n`;

// Write output
mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs', 'api.md'), md);
console.log(`✅ API docs generated → docs/api.md (${(md.length / 1024).toFixed(1)} kB)`);
